### ISSUE TITLE
Teamspeak crashes while trying to join a server with salty chat enabled 

### ISSUE THREAD

**Issue by peterfaker** [v10networkscom/saltychat-docs#56]
Basically what it says in the title. I am able to connect the server when it's disabled but i can't when it's enabled. I have a crash dump file to provide for the crash error
[ts3dump_1659375901020.zip](https://github.com/v10networkscom/saltychat-docs/files/9236062/ts3dump_1659375901020.zip)
.

**Comment by BlackFlash5** [comment]
According to the log you're running Windows 8.1, which we don't officially support.
In case you're running TeamSpeak in compatibility mode, disable it.
If you're actually using Windows 8.1 you should probably update since mainstream support ended 2018 and completely ends in January 2023 > see [Windows 8.1 lifecycle](https://docs.microsoft.com/en-us/lifecycle/products/windows-81).
